# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: timeline	
  username: root
  password: root
  host: 127.0.0.1
  port: 3306


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: timeline.test
  pool: 5
  username: root
  password: paswd
  host: localhost
